export const signInActionTypes = {
    REQUEST_ACTION: 'SIGN_IN_REQUEST_ACTION',
    SUCCESS_ACTION: 'SIGN_IN_SUCCESS_ACTION',
    FAILED_ACTION: 'SIGN_IN_FAILED_ACTION'
}

export const resetActionTypes = {
    RESET_AUTH_ACTION: 'RESET_AUTH_ACTION',
    RESET_POST_ACTION: 'RESET_POST_ACTION',
    RESET_IMAGE_ACTION: 'RESET_IMAGE_ACTION',
}

// ** Post
export const savePostActionTypes = {
    REQUEST_ACTION: 'SAVE_POST_REQUEST_ACTION',
    SUCCESS_ACTION: 'SAVE_POST_SUCCESS_ACTION',
    FAILED_ACTION: 'SAVE_POST_FAILED_ACTION'
}

export const postsActionTypes = {
    REQUEST_ACTION: 'POSTS_REQUEST_ACTION',
    SUCCESS_ACTION: 'POSTS_SUCCESS_ACTION',
    FAILED_ACTION: 'POSTS_FAILED_ACTION'
}

// ** image picker
export const imagePickerActionTypes = {
    SET_IMAGE: "SET_IMAGE"
}
